"""Localized strings used by the Faster-Whisper GUI."""

LANGUAGE_CODES = ("zh", "en")
LANGUAGE_LABELS = {"zh": "中文", "en": "English"}

TRANSLATIONS = {
    "zh": {
        "window_title": "Faster-Whisper GUI — VAD → ASR 转写工具",
        "input": "输入",
        "audio_file": "音频文件：",
        "subtitle_file": "字幕文件：",
        "model_path": "模型路径：",
        "cudnn_dir": "cuDNN 目录：",
        "allow_subtitle_mismatch": "允许字幕与音频文件名不同",
        "vad_parameters": "VAD 参数",
        "whisper_parameters": "Whisper 参数",
        "controls": "控制",
        "advanced": "高级",
        "log": "日志",
        "language": "语言：",
        "initial_prompt": "初始提示词：",
        "hotwords": "热词：",
        "beam_size": "束搜索大小：",
        "best_of": "候选数 (Best Of)：",
        "word_timestamps": "词级时间戳",
        "log_progress": "显示进度",
        "start_threshold": "语音起始阈值：",
        "end_threshold": "语音结束阈值：",
        "min_speech": "最短语音 (ms)：",
        "max_speech": "最长语音 (ms)：",
        "merge_silence": "合并静音 (ms)：",
        "extend_speech": "语音延展 (ms)：",
        "gui_language": "界面语言：",
        "browse": "浏览",
        "select_folder": "选择文件夹",
        "select_file": "选择文件",
        "media_files": "媒体文件",
        "subtitle_files": "字幕文件",
        "all_files": "所有文件",
        "save_config": "保存配置",
        "run_vad": "运行 VAD",
        "run_asr": "运行 ASR",
        "run_all": "一键运行",
        "cancel": "取消",
        "ready": "就绪",
        "running": "运行中…",
        "cancelling": "正在取消…",
        "config_saved": "💾 配置已保存到 gui_config.ini",
        "audio_required": "音频文件路径不能为空。",
        "audio_missing": "找不到音频文件：\n{path}",
        "ffmpeg_missing": "未找到 ffmpeg。\n\n请先下载解压 FFmpeg：\nhttps://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl-shared.zip\n\n并将包含 ffmpeg.exe 的目录添加到系统 PATH，然后重新启动本程序。",
        "threshold_order": "语音起始阈值（{start:.2f}）小于语音结束阈值（{end:.2f}），语音检测逻辑会倒挂，请调整参数。",
        "vad_duration_negative": "VAD 时长参数不能为负数。",
        "vad_duration_order": "最短语音（{min_ms} ms）大于最长语音（{max_ms} ms），请调整参数。",
        "model_required": "模型路径不能为空。",
        "model_missing": "找不到模型目录：\n{path}",
        "subtitle_required": "字幕文件路径不能为空——请先运行 VAD 或手动指定。",
        "subtitle_missing": "找不到字幕文件：\n{path}",
        "subtitle_mismatch": "字幕文件名（{subtitle}）与音频名（{audio}）不匹配，可能使用了其他音频的字幕，转写结果会错位。",
        "cudnn_warning": "cuDNN 目录不可用：\n{path}\n（目录不存在或其中没有 DLL 文件）\n本次运行将回退到 CPU 模式，速度较慢。",
        "validation_error": "校验错误",
        "notice": "提示",
        "runtime_error": "运行出错",
        "error_details": "详细错误信息请查看日志。",
        "confirm_exit": "确认退出",
        "exit_warning": "后台任务仍在运行，退出将中断任务并可能留下未完成的结果。\n\n确定要退出吗？",
        "vad_cancelled": "🛑 VAD 已取消，跳过。",
        "asr_cancelled": "🛑 ASR 已取消，跳过。",
        "task_cancelled": "🛑 任务已取消。",
        "cancelling_log": "🛑 正在取消任务…",
        "error_log": "❌ 错误：{error}",
        "vad_start": "🎤 正在运行 VAD（语音活动检测）…",
        "vad_audio": "   音频   : {path}",
        "vad_output": "   输出   : {path}",
        "vad_no_output": "❌ VAD 未生成 SRT 文件：{path}",
        "vad_done": "✅ VAD 完成 — 共 {count} 个语音段，音频时长 {duration:.1f}s",
        "srt_saved": "   SRT 已保存 → {path}",
        "vad_review": "👉 请检查/调整 VAD 字幕，然后点击 [运行 ASR]。",
        "vad_complete": "VAD 完成",
        "vad_complete_message": "在 {duration:.1f}s 音频中检测到 {count} 个语音段。\n\n输出文件：\n{path}\n\n请检查 SRT 文件，然后点击 [运行 ASR] 进行转写。",
        "model_reuse": "   ♻️  模型已加载 — 复用缓存实例",
        "model_reload": "   🔄 模型配置已更改，正在加载新实例 …",
        "model_first_load": "   ⏳ 首次加载 — 可能需要一些时间 …",
        "asr_start": "📝 正在运行 ASR（自动语音识别）…",
        "asr_model": "   模型    : {path}",
        "asr_audio": "   音频    : {path}",
        "asr_chunks": "   分块    : {path}",
        "asr_device": "   设备    : {device} / {compute_type}",
        "asr_language": "   语言    : {language}",
        "model_loading": "   正在加载 Whisper 模型 …",
        "transcribing": "   正在转写 …",
        "progress": "⏳ 正在转写第 {done}/{total} 条语音段 …",
        "asr_cancelled_output": "🛑 ASR 已取消 — 未生成最终 SRT。",
        "asr_done": "✅ ASR 完成 — 已转写 {count} 个语音段",
        "asr_complete": "ASR 完成",
        "asr_complete_message": "已转写 {count} 个语音段。\n\n输出文件：\n{path}",
        "no_subtitle": "❌ VAD 未生成字幕，已停止。",
        "skip_asr": "🛑 任务已取消，跳过 ASR。",
    },
    "en": {
        "window_title": "Faster-Whisper GUI — VAD → ASR Transcription",
        "input": "Input",
        "audio_file": "Audio File:",
        "subtitle_file": "Subtitle File:",
        "model_path": "Model Path:",
        "cudnn_dir": "cuDNN Directory:",
        "allow_subtitle_mismatch": "Allow subtitle and audio filenames to differ",
        "vad_parameters": "VAD Parameters",
        "whisper_parameters": "Whisper Parameters",
        "controls": "Controls",
        "advanced": "Advanced",
        "log": "Log",
        "language": "Language:",
        "initial_prompt": "Initial Prompt:",
        "hotwords": "Hotwords:",
        "beam_size": "Beam Size:",
        "best_of": "Best Of:",
        "word_timestamps": "Word Timestamps",
        "log_progress": "Log Progress",
        "start_threshold": "Start Threshold:",
        "end_threshold": "End Threshold:",
        "min_speech": "Min Speech (ms):",
        "max_speech": "Max Speech (ms):",
        "merge_silence": "Merge Silence (ms):",
        "extend_speech": "Extend Speech (ms):",
        "gui_language": "Interface Language:",
        "browse": "Browse",
        "select_folder": "Select Folder",
        "select_file": "Select File",
        "media_files": "Media Files",
        "subtitle_files": "Subtitle Files",
        "all_files": "All Files",
        "save_config": "Save Config",
        "run_vad": "Run VAD",
        "run_asr": "Run ASR",
        "run_all": "Run All",
        "cancel": "Cancel",
        "ready": "Ready",
        "running": "Running…",
        "cancelling": "Cancelling…",
        "config_saved": "💾 Config saved to gui_config.ini",
        "audio_required": "Audio file path is required.",
        "audio_missing": "Audio file not found:\n{path}",
        "ffmpeg_missing": "FFmpeg was not found.\n\nPlease download and extract FFmpeg:\nhttps://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl-shared.zip\n\nAdd the directory containing ffmpeg.exe to the system PATH, then restart this application.",
        "threshold_order": "The start threshold ({start:.2f}) is lower than the end threshold ({end:.2f}); adjust the VAD thresholds.",
        "vad_duration_negative": "VAD duration values cannot be negative.",
        "vad_duration_order": "Minimum speech duration ({min_ms} ms) is greater than maximum duration ({max_ms} ms); adjust the values.",
        "model_required": "Model path is required.",
        "model_missing": "Model directory not found:\n{path}",
        "subtitle_required": "Subtitle file path is required — run VAD first or specify one manually.",
        "subtitle_missing": "Subtitle file not found:\n{path}",
        "subtitle_mismatch": "Subtitle filename ({subtitle}) does not match the audio name ({audio}); the transcription may be misaligned.",
        "cudnn_warning": "cuDNN directory is unavailable:\n{path}\n(the directory does not exist or contains no DLL files)\nThis run will fall back to CPU mode, which is slower.",
        "validation_error": "Validation Error",
        "notice": "Notice",
        "runtime_error": "Runtime Error",
        "error_details": "See the log for detailed error information.",
        "confirm_exit": "Confirm Exit",
        "exit_warning": "A background task is still running. Exiting will interrupt it and may leave incomplete output.\n\nQuit anyway?",
        "vad_cancelled": "🛑 VAD cancelled, skipping.",
        "asr_cancelled": "🛑 ASR cancelled, skipping.",
        "task_cancelled": "🛑 Task cancelled.",
        "cancelling_log": "🛑 Cancelling task…",
        "error_log": "❌ Error: {error}",
        "vad_start": "🎤 Starting VAD (Voice Activity Detection)…",
        "vad_audio": "   Audio  : {path}",
        "vad_output": "   Output : {path}",
        "vad_no_output": "❌ VAD did not produce an SRT file: {path}",
        "vad_done": "✅ VAD complete — {count} segment(s), {duration:.1f}s audio",
        "srt_saved": "   SRT saved → {path}",
        "vad_review": "👉 Review or adjust the VAD subtitle, then click [Run ASR].",
        "vad_complete": "VAD Complete",
        "vad_complete_message": "Detected {count} speech segment(s) in {duration:.1f}s of audio.\n\nOutput:\n{path}\n\nReview the SRT file, then click [Run ASR] to transcribe.",
        "model_reuse": "   ♻️  Model already loaded — reusing cached instance",
        "model_reload": "   🔄 Model config changed, loading a new instance …",
        "model_first_load": "   ⏳ First load — this may take a moment …",
        "asr_start": "📝 Starting ASR (Automatic Speech Recognition)…",
        "asr_model": "   Model    : {path}",
        "asr_audio": "   Audio    : {path}",
        "asr_chunks": "   Chunks   : {path}",
        "asr_device": "   Device   : {device} / {compute_type}",
        "asr_language": "   Language : {language}",
        "model_loading": "   Loading Whisper model …",
        "transcribing": "   Transcribing …",
        "progress": "⏳ Transcribing chunk {done}/{total} …",
        "asr_cancelled_output": "🛑 ASR cancelled — no final SRT produced.",
        "asr_done": "✅ ASR complete — {count} segment(s) transcribed",
        "asr_complete": "ASR Complete",
        "asr_complete_message": "Transcribed {count} segment(s).\n\nOutput:\n{path}",
        "no_subtitle": "❌ VAD produced no subtitle, stopping.",
        "skip_asr": "🛑 Task cancelled, skipping ASR.",
    },
}